In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
print('type - ',type(iris)) # Bunch -> key value 로 이루어져있음
print('keys - ', iris.keys())

type -  <class 'sklearn.utils.Bunch'>
keys -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
print('target - ',iris.target)
print('data type - ',type(iris.target)) #-> 1차원 행렬
print()
print('target - ',iris.target_names)# setosa -> 0 으로 인코딩한게 타겟 값
print('data type - ',type(iris.target_names))

target -  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
data type -  <class 'numpy.ndarray'>

target -  ['setosa' 'versicolor' 'virginica']
data type -  <class 'numpy.ndarray'>


In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
pd.read_csv('C:/Users/shhmu/Documents/python_pandas/dataset/to_ex1.csv')

c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [7]:
import os
print(os.getcwd())


C:\Users\shhmu\Documents\machine_learning


In [8]:
print('target - ',iris.target)
print('data type - ',type(iris.target)) #-> 1차원 행렬
print()
print('target - ',iris.target_names)# setosa -> 0 으로 인코딩한게 타겟 값
print('data type - ',type(iris.target_names))

target -  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
data type -  <class 'numpy.ndarray'>

target -  ['setosa' 'versicolor' 'virginica']
data type -  <class 'numpy.ndarray'>


In [9]:
print('feature, target를 이용해서 데이터프레임을 만들기')
iris_frm = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_frm['target'] = iris.target
iris_frm

feature, target를 이용해서 데이터프레임을 만들기


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split 
from sklearn.tree            import DecisionTreeClassifier # 분류예측
from sklearn.metrics         import accuracy_score # 예측정확도

In [11]:
print('step 01.')
print()

a_train, a_test, b_train, b_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.04,
                                                shuffle = False, # 섞기?말지?
                                                random_state = 100)# 고정 값
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.04,
                                                shuffle = False, # 섞기?말지?
                                                random_state = 1)# 고정여부

step 01.



In [12]:
a_train.shape, a_test.shape, b_train.shape, b_test.shape

((144, 4), (6, 4), (144,), (6,))

In [13]:
print('train data - ',a_test)
print()

print('train data - ',x_test)


train data -  [[6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

train data -  [[6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [14]:
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.02,
                                                shuffle = False, # 섞기?말지?
                                                random_state = 1)# 고정여부

In [15]:
print('train data - ',x_test)
print()
print('train target - ',y_test)

train data -  [[6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

train target -  [2 2 2]


In [16]:
print('step 02. fit()')# 데이터 학습 모델 설정
print()

iris_dtc_model = DecisionTreeClassifier()
iris_dtc_model.fit(x_train, y_train)

step 02. fit()



DecisionTreeClassifier()

In [17]:
print('step 03. predict()')
print()

y_pred = iris_dtc_model.predict(x_test)
print('y_test - ',y_test)
print('y_test - ',y_pred)

step 03. predict()

y_test -  [2 2 2]
y_test -  [2 2 2]


In [18]:
print('step 04. 예측정확도 - ')
print()
print('acc - ',accuracy_score(y_test,y_pred)) 

step 04. 예측정확도 - 

acc -  1.0


In [19]:
display(iris_frm)
print()
print('type - ',type(iris_frm))

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]


type -  <class 'pandas.core.frame.DataFrame'>


In [20]:
print('iloc()이용해서 피처와 타겟을 추출한다면 - ')
iris_feature_frm =iris_frm.iloc[ : , 0:4]
iris_target_frm = iris_frm.iloc[ : , -1]
print('iris_feature_frm- ',type(iris_feature_frm))
print('iris_target_frm- ',type(iris_target_frm))

iloc()이용해서 피처와 타겟을 추출한다면 - 
iris_feature_frm-  <class 'pandas.core.frame.DataFrame'>
iris_target_frm-  <class 'pandas.core.series.Series'>


In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(iris_feature_frm,
                                                iris_target_frm,
                                                test_size=0.2,
                                                shuffle = True, # 섞기?말지?
                                                random_state = 100)

In [22]:
print('step 02. fit()')# 데이터 학습 모델 설정
print()

iris_dtc_model = DecisionTreeClassifier()
iris_dtc_model.fit(X_train, Y_train)

step 02. fit()



DecisionTreeClassifier()

In [23]:
print('step 03. predict()')
print()

y_pred = iris_dtc_model.predict(X_test)
print('y_test - ',Y_test)
print('y_test - ',y_pred, type(y_pred))
# 테스트 시 트레인 데이터가 들어가지 않게 조심해야한다.

step 03. predict()

y_test -  128    2
11     0
118    2
15     0
123    2
135    2
32     0
1      0
116    2
45     0
40     0
115    2
26     0
28     0
145    2
97     1
62     1
77     1
122    2
112    2
125    2
31     0
146    2
29     0
69     1
149    2
75     1
20     0
73     1
120    2
Name: target, dtype: int32
y_test -  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2] <class 'numpy.ndarray'>


In [24]:
print('step 04. 예측정확도 - ')
print()
print('acc - ',accuracy_score(Y_test,y_pred))

step 04. 예측정확도 - 

acc -  0.9666666666666667


In [25]:
from sklearn.model_selection import KFold, StratifiedKFold,cross_val_score,\
cross_validate 
# KFold, StratifiedKFold : 과적합 검사

In [26]:
from sklearn.datasets import load_iris
fold_iris = load_iris()
features = fold_iris.data
label = fold_iris.target

In [27]:
cv_acc = []
kfold = KFold(n_splits = 5)# 5개의 세트를 만듦(n_split = 5)
# 데이터가 불균등한 경우 KFold는 교차검증에 안 좋다.
fold_dct_model = DecisionTreeClassifier()
features = fold_iris.data
for train_idx, test_idx in kfold.split(features):
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx],label[test_idx]

    fold_dct_model.fit(X_train,y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    cv_acc.append(acc)
print('교차검증 평균 정확도 - ',np.mean(cv_acc))

교차검증 평균 정확도 -  0.9066666666666666


In [43]:
cv_acc = []
kfold = KFold(n_splits = 3)# 5개의 세트를 만듦(n_split = 5)
# 데이터가 불균등한 경우 KFold는 교차검증에 안 좋다.
fold_dct_model = DecisionTreeClassifier()
features = fold_iris.data

for train_idx, test_idx in kfold.split(features):

    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx],label[test_idx]
    print()
    print(y_train)
    fold_dct_model.fit(X_train,y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    cv_acc.append(acc)
print('교차검증 평균 정확도 - ',np.mean(cv_acc))
# 학습 데이터에 학습되지 않은 데이터를 테스트해서 정확도 -> 0
# KFold 의 문제점


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
교차검증 평균 정확도 -  0.0


In [37]:
fold_iris = load_iris()

features = fold_iris.data
label = fold_iris.target

numpy.ndarray

In [46]:
cv_acc = []
stf = StratifiedKFold(n_splits = 3)
fold_dct_model = DecisionTreeClassifier(random_state = 200)

for train_idx, test_idx in stf.split(features,label):
    x_train, x_test = features[train_idx], features[test_idx]
    y_train, y_test = label[train_idx], label[test_idx]
    print(y_train)
    print()
    fold_dct_model.fit(x_train,y_train)
    
    fold_pred = fold_dct_model.predict(x_test)
    acc = accuracy_score(y_test,fold_pred)
    cv_acc.append(acc)
print('교차검증 평균 정확도 - ',np.mean(cv_acc))
# 학습데이터가 골고루 섞인것을 볼 수 있다.
# split = 3일때 KFold보다 정확도가 증가했다.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

교차검증 평균 정확도 -  0.9666666666666667


In [47]:
fold_iris = load_iris()
features = fold_iris.data
label = fold_iris.target
dt_model = DecisionTreeClassifier(random_state = 100)

print('성능평가 acc , 교차검증 5회 수행 - ')
print('cross_val_score() - ')
print()

scores = cross_val_score(dt_model, 
                         features, label, scoring = 'accuracy' , cv = 5)

print('type - ',type(scores))
print('data - ', scores)
print('mean - ', np.round(np.mean(scores), 2))

성능평가 acc , 교차검증 5회 수행 - 
cross_val_score() - 

type -  <class 'numpy.ndarray'>
data -  [0.96666667 0.96666667 0.9        0.93333333 1.        ]
mean -  0.95
